# Generated by Django 3.1.7 on 2021-03-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.DecimalField(decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='building_age',
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='building_type',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Flat', 'Flat'), ('Town house', 'Town house'), ('Villa', 'Villa'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='floor',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='isFurniture',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='isSale',
            field=models.BooleanField(default=False),
        ),
    ]
