# Generated by Django 3.1.6 on 2021-03-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_ouruser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(choices=[(' İstanbul/Asya', ' İstanbul/Asya'), ('İstanbul/Avrupa', 'İstanbul/Avrupa'), ('Ankara', 'Ankara'), (' İzmir', ' İzmir'), ('Eskişehir', 'Eskişehir'), ('Adana', 'Adana'), ('Karabük', 'Karabük'), ('Uşak', 'Uşak'), ('Konya', 'Konya'), ('Antalya', 'Antalya'), ('Mersin', 'Mersin'), ('Diyarbakır', 'Diyarbakır'), ('Sakarya', 'Sakarya'), ('Eskişehir', 'Eskişehir'), ('Van', 'Van'), ('Kars', 'Kars'), ('Amasya', 'Amasya'), ('Balıkesir', 'Balıkesir'), ('Muğla', 'Muğla'), ('Batman', 'Batman'), ('Kocaeli', 'Kocaeli')], max_length=255, null=True),
        ),
    ]
