# Generated by Django 3.1.6 on 2021-03-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210327_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='isFurniture',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], max_length=50, null=True),
        ),
    ]
