# Generated by Django 3.1.4 on 2021-04-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210328_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='room',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
    ]
