# Generated by Django 3.2 on 2021-05-08 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210508_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='user',
            new_name='userip',
        ),
    ]
