# Generated by Django 3.2 on 2021-05-08 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_user_visitor_userip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
